name: "Node App"
services:
  app:
    container_name: "node_app"
    build:
      context: "./node app"
      dockerfile: Dockerfile
    image: "node_app_image"
    ports:
      - "5000:5000"
    volumes:
      - my-imgs:/app/uploads
    develop:
      watch:
        - path: "./node app"
          action: sync
          target: "/app"
          ignore:
            - "node_modules"
            


volumes:
  my-imgs:
    
    

